#!/usr/bin/env node
import { execFileSync } from "node:child_process"
import { createRequire } from "node:module"
import { mkdirSync, rmSync, writeFileSync } from "node:fs"
import { dirname, resolve } from "node:path"

const repoRoot = resolve(import.meta.dirname, "../../..")
const requireFromBackend = createRequire(resolve(repoRoot, "apps/backend/package.json"))
const sharp = requireFromBackend("sharp")
const outputRoot = resolve(repoRoot, "apps/macos/Resources")
const iconsetDir = resolve(outputRoot, "AppIcon.iconset")
const appIconPath = resolve(outputRoot, "AppIcon.icns")
const menuBarIconPath = resolve(outputRoot, "MenuBarIconTemplate.png")

const brandRed = "#B31329"
const markPath =
  "M9.11417 3.27085C7.07981 5.07258 6.27528 7.52225 6.06208 9.82282C5.69559 13.7775 8.07813 17.6442 11.8877 18.7668C14.3032 19.4786 16.5687 19.4396 17.8453 19.0728C20.5682 18.3858 27.5283 14.691 30.0323 3.27085C20.3214 -2.65297 12.0407 0.802589 9.11417 3.27085Z"
const berryPath =
  "M29.6234 32.4553C33.2053 31.046 37.1773 33.4847 36.1098 37.1829L32.4652 49.8059C30.4521 56.7791 23.8675 61.4203 16.6234 60.9709C9.37926 60.5215 3.41819 55.1016 2.28262 47.9329C1.87132 45.3384 3.31873 42.8069 5.76309 41.845L29.6234 32.4553ZM26.8744 15.7112C28.9962 16.8067 30.9413 18.3366 32.5707 20.2942C34.9457 23.1477 33.0888 27.1221 29.6342 28.4817L5.50919 37.9768C3.18794 38.8903 0.617004 37.4201 0.22696 34.9563C-0.728423 28.924 1.36914 22.8103 5.82657 18.635C5.96887 18.5017 6.11292 18.3713 6.25821 18.2434C7.21088 19.403 8.44168 20.3309 9.89883 20.8928C13.2528 22.1861 16.5559 22.1959 18.31 21.6858C20.1647 21.2121 23.6489 19.5659 26.8744 15.7112Z"

const appIconSvg = `
<svg width="1024" height="1024" viewBox="0 0 1024 1024" xmlns="http://www.w3.org/2000/svg">
  <defs>
    <linearGradient id="bg" x1="250" y1="128" x2="774" y2="896" gradientUnits="userSpaceOnUse">
      <stop offset="0" stop-color="#CC1B35"/>
      <stop offset="0.58" stop-color="${brandRed}"/>
      <stop offset="1" stop-color="#8F0F22"/>
    </linearGradient>
    <filter id="shadow" x="48" y="52" width="928" height="948" filterUnits="userSpaceOnUse" color-interpolation-filters="sRGB">
      <feDropShadow dx="0" dy="22" stdDeviation="26" flood-color="#2C0710" flood-opacity="0.22"/>
      <feDropShadow dx="0" dy="4" stdDeviation="7" flood-color="#2C0710" flood-opacity="0.18"/>
    </filter>
  </defs>
  <rect x="92" y="72" width="840" height="840" rx="186" fill="url(#bg)" filter="url(#shadow)"/>
  <path d="M9.11417 3.27085C7.07981 5.07258 6.27528 7.52225 6.06208 9.82282C5.69559 13.7775 8.07813 17.6442 11.8877 18.7668C14.3032 19.4786 16.5687 19.4396 17.8453 19.0728C20.5682 18.3858 27.5283 14.691 30.0323 3.27085C20.3214 -2.65297 12.0407 0.802589 9.11417 3.27085Z" fill="#FFFFFF" transform="translate(332 205) scale(9.72)"/>
  <path fill-rule="evenodd" clip-rule="evenodd" d="${berryPath}" fill="#FFFFFF" transform="translate(332 205) scale(9.72)"/>
</svg>`

const menuBarSvg = `
<svg width="36" height="36" viewBox="0 0 36 36" xmlns="http://www.w3.org/2000/svg">
  <g transform="translate(9 3) scale(0.49)">
    <path d="${markPath}" fill="#000000"/>
    <path fill-rule="evenodd" clip-rule="evenodd" d="${berryPath}" fill="#000000"/>
  </g>
</svg>`

const iconSizes = [
  ["icon_16x16.png", 16],
  ["icon_16x16@2x.png", 32],
  ["icon_32x32.png", 32],
  ["icon_32x32@2x.png", 64],
  ["icon_128x128.png", 128],
  ["icon_128x128@2x.png", 256],
  ["icon_256x256.png", 256],
  ["icon_256x256@2x.png", 512],
  ["icon_512x512.png", 512],
  ["icon_512x512@2x.png", 1024],
]

mkdirSync(outputRoot, { recursive: true })
rmSync(iconsetDir, { recursive: true, force: true })
mkdirSync(iconsetDir, { recursive: true })

await Promise.all(
  iconSizes.map(([name, size]) =>
    sharp(Buffer.from(appIconSvg))
      .resize(size, size)
      .png()
      .toFile(resolve(iconsetDir, name))
  )
)

await sharp(Buffer.from(menuBarSvg))
  .resize(36, 36)
  .png()
  .toFile(menuBarIconPath)

rmSync(appIconPath, { force: true })
execFileSync("iconutil", ["-c", "icns", iconsetDir, "-o", appIconPath], {
  stdio: "inherit",
})
rmSync(iconsetDir, { recursive: true, force: true })

writeFileSync(
  resolve(dirname(appIconPath), "ICON_SOURCES.md"),
  [
    "# macOS Icon Sources",
    "",
    "Generated by `apps/macos/Scripts/generate-icons.mjs` from the existing Mulberry icon mark used in `apps/web/public/brand/icon-color.svg` and `docs/store-assets/play-store-icon.svg`.",
    "",
    "- `AppIcon.icns`: macOS app bundle icon.",
    "- `MenuBarIconTemplate.png`: monochrome template image for the status bar item.",
    "",
  ].join("\n")
)

console.log(`Wrote ${appIconPath}`)
console.log(`Wrote ${menuBarIconPath}`)
