package com.subhajit.mulberry.core.ui

object TestTags {
    const val BOOTSTRAP_SCREEN = "bootstrap_screen"
    const val AUTH_LANDING_SCREEN = "auth_landing_screen"
    const val AUTH_GOOGLE_BUTTON = "auth_google_button"
    const val ONBOARDING_NAME_SCREEN = "onboarding_name_screen"
    const val ONBOARDING_NAME_CONTINUE_BUTTON = "onboarding_name_continue_button"
    const val ONBOARDING_ENTER_CODE_BUTTON = "onboarding_enter_code_button"
    const val ONBOARDING_DETAILS_SCREEN = "onboarding_details_screen"
    const val ONBOARDING_DETAILS_SUBMIT_BUTTON = "onboarding_details_submit_button"
    const val ONBOARDING_WALLPAPER_SCREEN = "onboarding_wallpaper_screen"
    const val ONBOARDING_WALLPAPER_SETUP_BUTTON = "onboarding_wallpaper_setup_button"
    const val ONBOARDING_WALLPAPER_UPLOAD_BUTTON = "onboarding_wallpaper_upload_button"
    const val ONBOARDING_WALLPAPER_BACKGROUND_SECTION = "onboarding_wallpaper_background_section"
    const val ONBOARDING_WALLPAPER_DONE_BUTTON = "onboarding_wallpaper_done_button"
    const val PAIRING_HUB_SCREEN = "pairing_hub_screen"
    const val PAIRING_CREATE_CODE_BUTTON = "pairing_create_code_button"
    const val PAIRING_ENTER_CODE_BUTTON = "pairing_enter_code_button"
    const val INVITE_CODE_SCREEN = "invite_code_screen"
    const val INVITE_CODE_SUBMIT_BUTTON = "invite_code_submit_button"
    const val INVITE_ACCEPTANCE_SCREEN = "invite_acceptance_screen"
    const val INVITE_ACCEPT_BUTTON = "invite_accept_button"
    const val INVITE_DECLINE_BUTTON = "invite_decline_button"
    const val PAIRING_DEMO_BUTTON = "pairing_demo_button"
    const val HOME_SCREEN = "home_screen"
    const val HOME_SETTINGS_BUTTON = "home_settings_button"
    const val HOME_SHARE_INVITE_BUTTON = "home_share_invite_button"
    const val HOME_INVITE_SHEET = "home_invite_sheet"
    const val HOME_OPEN_CANVAS_BUTTON = "home_open_canvas_button"
    const val HOME_OPEN_LOCKSCREEN_BUTTON = "home_open_lockscreen_button"
    const val CANVAS_SCREEN = "canvas_screen"
    const val DRAWING_CANVAS = "drawing_canvas"
    const val BRUSH_WIDTH_SLIDER = "brush_width_slider"
    const val ERASER_BUTTON = "eraser_button"
    const val CLEAR_BUTTON = "clear_button"
    const val CLEAR_CONFIRM_BUTTON = "clear_confirm_button"
    const val LOCKSCREEN_SCREEN = "lockscreen_screen"
    const val LOCKSCREEN_OPEN_WALLPAPER_BUTTON = "lockscreen_open_wallpaper_button"
    const val LOCKSCREEN_SELECT_BACKGROUND_BUTTON = "lockscreen_select_background_button"
    const val LOCKSCREEN_CLEAR_BACKGROUND_BUTTON = "lockscreen_clear_background_button"
    const val LOCKSCREEN_REFRESH_SNAPSHOT_BUTTON = "lockscreen_refresh_snapshot_button"
    const val SETTINGS_SCREEN = "settings_screen"
    const val SETTINGS_DEVELOPER_SECTION = "settings_developer_section"
    const val SETTINGS_RESET_BUTTON = "settings_reset_button"
    const val SETTINGS_LOGOUT_BUTTON = "settings_logout_button"
}
