package com.subhajit.mulberry.ui.theme

import androidx.compose.ui.graphics.Color

val MulberryPrimary = Color(0xFFB31329)
val MulberryPrimaryDark = Color(0xFF7E0D1D)
val MulberryPrimaryLight = Color(0xFFF7DDE2)
val MulberryAccent = Color(0xFFFF6A2A)
val MulberryInk = Color(0xFF171016)
val MulberryMutedInk = Color(0xFF6F5961)
val MulberrySurface = Color(0xFFFFFAFA)
val MulberrySurfaceVariant = Color(0xFFF5EAED)
val MulberryDarkBackground = Color(0xFF101010)
val MulberryDarkSurface = Color(0xFF181818)
val MulberryDarkSurfaceVariant = Color(0xFF242424)
val MulberryDarkInk = Color(0xFFFFFFFF)
val MulberryDarkMutedInk = Color(0xFFBDBDBD)
val MulberryDarkSoftSurface = Color(0xFF171314)
val MulberryDarkSoftSurfaceAlt = Color(0xFF1B1517)
val MulberryDarkSoftSurfaceStrong = Color(0xFF24181B)
val MulberryDarkSoftSurfaceSelected = Color(0xFF2A1C20)
val MulberryDarkSoftBorder = Color(0xFF2F2125)
val MulberryDarkFieldSurface = Color(0xFF1C1C1C)
val MulberryDarkPreviewFrame = Color(0xFF2F2F2F)
val MulberryDarkHandle = Color(0xFF4A4A4A)
val MulberryError = Color(0xFFB3261E)
val MulberrySuccess = Color(0xFF2E7D32)
